:icons: font
:toc: preamble
:hardbreaks:
:imagesdir: images
:data-uri:
:authors: Michał Jędrzejczyk, Hubert Milczarek, Kamil Jankowski

= Angular

Czym jest Angular?
Angular jest platformą oraz szkieletem dla projektowania oraz rozwoju wydajnych jednostronicowych aplikacji (SAP - single-page app =! single page website).

Jego podstawowym elementem budulcowym są komponenty.
Każdy komponent składa się z poniższych elementów:

* szablonu HTML, określającego wygląd strony;
* klasy TypeScript, definiującej zachowania naszego komponentu;
* selektora CSS, definiującego sposób użycia komponentu w szablonie HTML;
* opcjonalnie, szablonu stylu CSS, jaki ma być zastosowany dla komponentu.

Podczas tworzenia komponentu przy pomocy _cli_ powyższe elementy zostaną wygenerowane automatycznie.

== Instalacja angulara

[source: bash]
----
npm install -g @angular/cli
----

Jeśli nie posiadasz zainstalowanego menedżera pakietów `npm`, użyj poniższej instrukcji:
https://www.npmjs.com/get-npm

[NOTE]
====
By rozpocząć pracę z projektem należy zainstalować niezbędne pakiety (wewnątrz projektu):
- _translate_ - tłumaczenie
- _toastr_ - powiadomienia okienkowe
- _material_ - komponenty pomocnicze
- _animations_ - animacje

[source: bash]
----
npm install @ngx-translate/core
npm install ngx-toastr --save
npm install --save @angular/material @angular/cdk
npm install --save @angular/animations
----
====

== "Hello World" - zadanie wprowadzające

. Utworzenie startowego projektu angulara:
+
[source: bash]
----
ng new workshop-project
----
+
* W przypadku pojawienia się błędów:
+
----
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
See "/tmp/ng-Rl1vk2/angular-errors.log" for further details.
----
Uruchom poniższą instrukcję w folderze z projektem:
+
[source: bash]
----
npm install --save-dev @angular-devkit/build-angular
----
+
* W przypadku pojawienia się błędu:
+
----
An unhandled exception occurred: Cannot find module '@angular/compiler-cli'
----
Uruchom poniższą instrukcję w folderze z projektem:
+
[source: bash]
----
npm install
----
+
. Zapoznaj się z instrukcjami ze strony startowej projektu:
+
[source: bash]
----
cd workshop-project
ng serve --open
----
Po więcej informacji możesz sięgnąć do dokumentacji (Źródła)
+
. Usuń istniejącą zawartość strony i zastąp ją pojedynczym nagłówkiem _Hello World!_

== "Moje statki" - zadanie

NOTE: Repozytorium z rozwiązaniem zadania: https://github.com/Kamil-Jankowski/Angular-workshop

. Utwórz nowy projekt wykorzystując instrukcję poznaną w poprzednim zadaniu.
. Utwórz komponent _moje_statki_
. Utwórz interfejs _statek_ zawierający pola `id` oraz `name`
. Wewnątrz komponentu _moje_statki_ dodaj statek oraz wyświetlanie szczegółów statku (id + name) w szablonie html.
. Wewnątrz komponentu _moje_statki_ umieść formularz umożliwiający dodawanie nowego statku używając składni `[(ngModel)]`.
+
Aby powyższy formularz zadziałał dodaj do `app.module.ts`:
+
[source: typescript]
----
import { FormsModule } from '@angular/forms'; // <-- NgModel lives here
(...)
imports: [
  BrowserModule,
  FormsModule
],
----
+
NOTE: Na tym etapie powinieneś posiadać kod przypominający ten z migawki _Ship details_

. Dodaj do projektu listę okrętów w nowej klasie:
+
[source: bash]
----
ng generate class mock-statki
----
+
Przykładowa zawartość pliku:
+
[source: typescript]
----
import { Ship } from './ship';

export const SHIPS: Ship[] = [
  { id: 11, name: 'Grom' },
  { id: 12, name: 'Błyskawica' },
  { id: 13, name: 'Orzeł' },
];
----

. Zaimportuj powyższą listę do komponentu `statki` oraz przypisz ją do zmiennej.
. Używając instrukcji `*ngFor` wypisz elementy listy:
+
[source: html]
----
<h2>My Ships</h2>
<ul class="ships">
    <li *ngFor="let ship of ships"
    [class.selected]="ship === selectedShip"
    (click)="onSelect(ship)">
    <span class="badge">{{ship.id}}</span> {{ship.name}}
  </li>
</ul>
----

. Zdefiniuj arkusz stylu dla komponentu `statki` zgodnie z poniższym przykładem:
+
----
/* shipsComponent's private CSS styles */
.ships {
    margin: 0 0 2em 0;
    list-style-type: none;
    padding: 0;
    width: 15em;
  }
  .ships li {
    cursor: pointer;
    position: relative;
    left: 0;
    background-color: #EEE;
    margin: .5em;
    padding: .3em 0;
    height: 1.6em;
    border-radius: 4px;
  }
  .ships li:hover {
    color: #607D8B;
    background-color: #DDD;
    left: .1em;
  }
  .ships li.selected {
    background-color: #CFD8DC;
    color: white;
  }
  .ships li.selected:hover {
    background-color: #BBD8DC;
    color: white;
  }
  .ships .badge {
    display: inline-block;
    font-size: small;
    color: white;
    padding: 0.8em 0.7em 0 0.7em;
    background-color:#405061;
    line-height: 1em;
    position: relative;
    left: -1px;
    top: -4px;
    height: 1.8em;
    margin-right: .8em;
    border-radius: 4px 0 0 4px;
  }
----

. W jednym z poprzednich kroków dodaliśmy zdarzenie związane z kliknięciem elementu na liście. Dodaj obsługującą je metodę.
. Dostosuj sekcję szczegółów stworzoną w poprzednim etapie tak, aby wyświetlała zaznaczony okręt.
+
Jeśli żaden okręt nie jest zaznaczony, użyj instrukcji
+
[source: html]
----
<div *ngIf="selectedShip"> (...) </div>
----
+
Dzięki temu, sekcja szczegółów będzie widoczna tylko po kliknięciu na jeden z okrętów.
+
NOTE: Na tym etapie powinieneś posiadać kod przypominający ten z migawki _Interactive list of ships_

. Wydziel osobny komponent dla widoku szczegółów okrętu: _statek-detale_
+
Aby można było wykorzystać obiekt wewnątrz innych komponentów musi on posiadać adnotację `@Input`
+
NOTE: Na tym etapie powinieneś posiadać kod przypominający ten z migawki _Ship Detail component_

. Utwórz serwis _statki_
+
[source: bash]
----
ng generate service statki
----
+
Następnie, dodaj do serwisu metodę służącą do pobierania statków:
+
[source: typescript]
----
  getShips(): Ship[] {
    return SHIPS;
  }
----
. Zaktualizuj kod komponentu _moje_statki_ tak by posiadał zwykłą deklarację zmiennej tablicowej `statki`.
Następnie dodaj do niego metodę pobierającą statki (wykorzystującą metodę z serwisu _statki_).
+
[source: typescript]
----
  getShips(): void {
    this.ships = this.shipsService.getShips();
  }
----
+
Pamiętaj, aby dodać odpowiednią instrukcję w metodzie inicjalizującej komponent.
+
Aby móc korzystać ze zdefiniowanego serwisu dodaj do komponentu niezbędne importy oraz zależności:
+
[source: typescript]
----
import { ShipsService } from '../ships.service';
(...)
  constructor(private shipsService: ShipsService) { }
----

. Tak zdefiniowane metody sprawdzają się w statycznym środowisku, ale nie nadają się do pracy z protokołem http.
+
Dokonaj zmian w serwisie pozwalających na wykorzystanie klasy `Observable`, ponieważ tego typu obiekty będą zwracane przez metody klienta http.
+
[source: typescript]
----
import { Observable, of } from 'rxjs';
(...)
  getShips(): Observable<Ship[]> {
    return of(SHIPS);
  }
----
+
Podobnie należy zmienić metodę w komponencie _moje_statki_:
+
[source: typescript]
----
  getShips(): void {
    this.shipsService.getShips()
                     .subscribe(ships => this.ships = ships);
  }
----
+
Takie podejście jest zwane podejściem asynchronicznym i będzie ono działać również przy wysyłaniu zapytań do serwera.
+
NOTE: Na tym etapie powinieneś posiadać kod przypominający ten z migawki _Ships service_

. Dodaj do aplikacji serwisy HTTP:
+
W `app.module.ts` dodaj poniższe linie:
+
[source: typescript]
----
import { HttpClientModule } from '@angular/common/http';
(...)
@NgModule({
  imports: [
    HttpClientModule,
  ],
})
----

. Wykorzystując _in-memory-web-api_ zasymuluj serwer
+
[source:bash]
----
npm install angular-in-memory-web-api --save
ng generate service InMemoryData
----
+
Zawartość pliku:
+
[source: typescript]
----
import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Statek } from './statek';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const statki = [
      { id: 11, name: 'Grom' },
      { id: 12, name: 'Błyskawica' },
      { id: 13, name: 'Orzeł' },
    ];
    return {statki};
  }

  genId(statki: statek[]): number {
    return statki.length > 0 ? Math.max(...statki.map(statek => statek.id)) + 1 : 11;
  }
}
----
+
Następnie dodaj odpowiednie importy do pliku `app.module.ts`:
+
[source: typescript]
----
import { HttpClientInMemoryWebApiModule } from 'angular-in-memory-web-api';
import { InMemoryDataService } from './in-memory-data.service';
(...)
  HttpClientModule,

  // The HttpClientInMemoryWebApiModule module intercepts HTTP requests
  // and returns simulated server responses.
  // Remove it when a real server is ready to receive requests.
  HttpClientInMemoryWebApiModule.forRoot(InMemoryDataService, { dataEncapsulation: false }
)
----
. Dodaj niezbędne importy w serwisie `statki`, a następnie dodaj zależność do klienta w konstruktorze.
+
[source: typescript]
----
import { HttpClient, HttpHeaders } from '@angular/common/http';
----

. Zdefiniuj zmienną, która będzie określała Twój zasób dla REST API, na przykład `api/ships`.
. Korzystając z utworzonej zmiennej popraw metodę _get_ w taki sposób, by wykorzystywała klienta http (`http.get<Array[]>(url)).
+
Teraz możesz usunąć klasę _mock_, która przechowywała statki. Nie jest już potrzebna. Jeśli będziesz chciał połączyć się z rzeczywistym serwerem, wystarczy, że usuniesz przechwytywanie zapytań z klasy `app.module.ts` i zmienisz zmienną dla zasobu w serwisie `statki`.
. Wewnątrz utworzonego serwisu dodaj metodę, która będzie dodawać statek do listy, oraz metodę pozwalająca na jego usunięcie.
+
.. Dodawanie:
+
[source: html]
----
<div>
  <label>Ship name:
    <input #shipName />
  </label>
  <!-- (click) passes input value to add() and then clears the input -->
  <button (click)="add(shipName.value); shipName.value=''">
    Add
  </button>
</div>
----
+
[source: typescript]
----
  /** POST: add a new ship to the server */
  addShip(ship: Ship): Observable<Ship> {
    console.log("Ships service: Posting new ship to the server");
    return this.http.post<Ship>(this.shipsUrl, ship, this.httpOptions);
  }
----
+
[source: typescript]
----
  add(name: string): void {
    name = name.trim();
    if (!name) { return; }
    this.shipsService.addShip({ name } as Ship)
      .subscribe((ship: Ship) => {
        this.ships.push(ship);
      });
  }
----
.. Usuwanie:
+
[source: html]
----
<button class="delete" title="delete ship" (click)="delete(ship)">x</button>
----
+
[source: typescript]
----
  /** DELETE: delete the ship from the server */
  deleteShip(ship: Ship | number): Observable<Ship> {
    const id = typeof ship === 'number' ? ship : ship.id;
    const url = `${this.shipsUrl}/${id}`;
    console.log(`Ships service: Removing ship number ${id} from the server`);
    return this.http.delete<Ship>(url, this.httpOptions);
  }
----
+
[source: typescript]
----
  delete(ship: Ship): void {
    this.ships = this.ships.filter(sh => sh !== ship);
    this.shipsService.deleteShip(ship).subscribe();
  }
----

NOTE: Na tym etapie powinieneś posiadać kod przypominający ten z migawki _Ships workshop complete_

Gotowe - gratulacje!

= Źródła

https://angular.io/docs

